// src/lib/export.ts
// Client-side PDF + DOCX export for generated policies.
// Dynamic-imports jspdf / docx only when a user clicks download.
// Supports Unicode rendering via Noto Sans font family for non-Latin scripts.

import type { GeneratedPolicy } from '@/lib/generator';
import { getFontForLanguage, getSecondaryFont, fetchFont, type FontInfo } from '@/lib/fonts';

/** Localization overrides for PDF/DOCX export. All fields optional — English defaults used when omitted. */
export interface ExportOverrides {
  preparedBy?: string;
  generatedBy?: string;
  pageLabel?: string;
  filename?: string;
  /** Language code (e.g. 'es', 'ar', 'ko') for Unicode font selection. Defaults to 'en'. */
  language?: string;
}

// ── Helpers ──────────────────────────────────────────────────

function stripMarkdownInline(text: string): string {
  return text
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/(^|[^*])\*([^*]+)\*(?!\*)/g, '$1$2')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1');
}

function triggerDownload(blob: Blob, filename: string) {
  const isDocx = filename.endsWith('.docx');
  const mimedBlob = blob.type.startsWith('application/')
    ? blob
    : new Blob([blob], {
        type: isDocx
          ? 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
          : 'application/pdf'
      });
  const url = URL.createObjectURL(mimedBlob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

/**
 * Converts an ArrayBuffer to a binary string (required by jsPDF's addFileToVFS).
 */
function arrayBufferToBinaryString(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]!);
  }
  return binary;
}

/**
 * Checks whether a string contains primarily non-Latin characters
 * (CJK, Arabic, Devanagari, etc.) to determine if we need special font handling.
 */
function isLatinScript(langCode: string): boolean {
  return ['en', 'de', 'es', 'fr', 'pt', 'nl', 'tr', 'vi', 'ru'].includes(langCode);
}

// ── PDF Export ───────────────────────────────────────────────

export async function exportPdf(policy: GeneratedPolicy, overrides?: ExportOverrides): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  const langCode = overrides?.language ?? 'en';
  const useCustomFont = langCode !== 'en' && !isLatinScript(langCode);

  // ── Load & register Unicode font if needed ───────────────────
  let primaryFontId = 'helvetica';
  let primaryFontName = 'Noto Sans';
  let hasCustomFont = false;

  if (useCustomFont) {
    try {
      const primaryFont = getFontForLanguage(langCode);
      const buffer = await fetchFont(primaryFont);
      const binaryStr = arrayBufferToBinaryString(buffer);
      const vfsName = `NotoSans-${langCode}.ttf`;

      doc.addFileToVFS(vfsName, binaryStr);
      doc.addFont(vfsName, 'noto', 'normal');
      primaryFontId = 'noto';
      primaryFontName = primaryFont.name;
      hasCustomFont = true;
    } catch (err) {
      console.warn(`Failed to load font for ${langCode}, falling back to Helvetica:`, err);
    }
  }

  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = margin;

  // Header & footer on every page (rendered via internal pages filter)
  const preparedBy = (overrides?.preparedBy ?? 'Prepared by {businessName}').replace('{businessName}', policy.businessName);
  const generatedBy = overrides?.generatedBy ?? 'Generated by PrivacyPolGen.com';
  const pageLabel = overrides?.pageLabel ?? 'Page';
  const filename = overrides?.filename ?? 'privacy-policy';

  // Set the active font
  const setFont = (style: 'normal' | 'bold' | 'italic' = 'normal') => {
    if (hasCustomFont) {
      // Custom Noto Sans only has 'normal' weight — use it for all styles
      doc.setFont(primaryFontId, 'normal');
    } else {
      doc.setFont('helvetica', style);
    }
  };

  const addHeaderFooter = (pageNum: number) => {
    // Header
    doc.setFontSize(8);
    doc.setTextColor(160);
    setFont();
    doc.text(preparedBy, margin, 10);
    // Footer
    doc.text(generatedBy, margin, pageH - 8);
    const pageStr = `${pageLabel} ${pageNum}`;
    doc.text(pageStr, pageW - margin - doc.getTextWidth(pageStr), pageH - 8);
  };

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - 20) {
      addHeaderFooter(doc.internal.getNumberOfPages());
      doc.addPage();
      y = margin;
    }
  };

  const lines = policy.markdown.split('\n');

  for (const raw of lines) {
    const line = raw.trimEnd();

    // Empty line — small gap
    if (line.length === 0) {
      y += 3;
      continue;
    }

    // H1 — centered title
    if (/^# /.test(line) && !/^## /.test(line)) {
      ensureSpace(18);
      doc.setFontSize(20);
      setFont('bold');
      doc.setTextColor(9);
      const title = sanitizeForPdf(stripMarkdownInline(line.replace(/^# /, '')));
      doc.text(title, pageW / 2, y + 7, { align: 'center' });
      y += 14;
      continue;
    }

    // H2 — section heading
    if (/^## /.test(line)) {
      ensureSpace(16);
      y += 4;
      doc.setFontSize(13);
      setFont('bold');
      doc.setTextColor(9);
      const heading = sanitizeForPdf(stripMarkdownInline(line.replace(/^## /, '')));
      doc.text(heading, margin, y + 5);
      y += 6;
      // Rule under heading
      doc.setDrawColor(200);
      doc.setLineWidth(0.3);
      doc.line(margin, y, pageW - margin, y);
      y += 5;
      continue;
    }

    // H3 — sub-heading
    if (/^### /.test(line)) {
      ensureSpace(12);
      y += 3;
      doc.setFontSize(11);
      setFont('bold');
      doc.setTextColor(9);
      const heading = sanitizeForPdf(stripMarkdownInline(line.replace(/^### /, '')));
      doc.text(heading, margin, y + 4);
      y += 7;
      continue;
    }

    // Blockquote — disclaimer (italic, muted)
    if (/^>\s/.test(line)) {
      ensureSpace(20);
      doc.setFontSize(8);
      setFont('italic');
      doc.setTextColor(130);
      const text = sanitizeForPdf(stripMarkdownInline(line.replace(/^>\s*/, '')));
      const split = doc.splitTextToSize(text, contentW - 4);
      for (const ln of split) {
        ensureSpace(4);
        doc.text(ln, margin + 2, y);
        y += 3.5;
      }
      y += 2;
      continue;
    }

    // Italic preamble
    if (/^\*[^*]+\*$/.test(line) && !/\*\*/.test(line)) {
      ensureSpace(10);
      doc.setFontSize(9);
      setFont('italic');
      doc.setTextColor(130);
      const text = sanitizeForPdf(stripMarkdownInline(line.replace(/^\*/, '').replace(/\*$/, '')));
      const split = doc.splitTextToSize(text, contentW);
      for (const ln of split) {
        ensureSpace(4);
        doc.text(ln, margin, y);
        y += 4;
      }
      y += 1;
      continue;
    }

    // Bold subtitle line (e.g. "Last updated: ...")
    if (/^\*\*[^*]+\*\*$/.test(line) || /^\*\*[^*]+\*\*:?\s/.test(line)) {
      ensureSpace(8);
      doc.setFontSize(9);
      setFont('bold');
      doc.setTextColor(120);
      const text = sanitizeForPdf(stripMarkdownInline(line));
      doc.text(text, margin, y + 4);
      y += 7;
      continue;
    }

    // List item
    if (/^[-*]\s+/.test(line)) {
      ensureSpace(6);
      doc.setFontSize(10);
      setFont();
      doc.setTextColor(50);
      const text = sanitizeForPdf(stripMarkdownInline(line.replace(/^[-*]\s+/, '')));
      const split = doc.splitTextToSize(text, contentW - 6);
      doc.text('\u2022', margin + 2, y);
      for (let i = 0; i < split.length; i++) {
        ensureSpace(4);
        doc.text(split[i]!, margin + 7, y);
        y += 4;
      }
      y += 1;
      continue;
    }

    // Ordered list
    if (/^\d+\.\s+/.test(line)) {
      ensureSpace(6);
      doc.setFontSize(10);
      setFont();
      doc.setTextColor(50);
      const text = sanitizeForPdf(stripMarkdownInline(line.replace(/^\d+\.\s+/, '')));
      const split = doc.splitTextToSize(text, contentW - 6);
      doc.text(line.match(/^\d+\./)![0], margin + 2, y);
      for (let i = 0; i < split.length; i++) {
        ensureSpace(4);
        doc.text(split[i]!, margin + 9, y);
        y += 4;
      }
      y += 1;
      continue;
    }

    // Regular paragraph
    ensureSpace(8);
    doc.setFontSize(10);
    setFont();
    doc.setTextColor(50);
    const text = sanitizeForPdf(stripMarkdownInline(line));
    const split = doc.splitTextToSize(text, contentW);
    for (const ln of split) {
      ensureSpace(4);
      doc.text(ln, margin, y);
      y += 4.5;
    }
    y += 1;
  }

  // Header/footer on first page too
  try {
    addHeaderFooter(doc.internal.getNumberOfPages());
    doc.save(`${filename}.pdf`);
  } catch (err) {
    console.error('PDF export failed:', err);
    throw new Error('Failed to generate PDF: ' + (err instanceof Error ? err.message : String(err)));
  }
}

// ── DOCX Export ──────────────────────────────────────────────

export async function exportDocx(policy: GeneratedPolicy, overrides?: ExportOverrides): Promise<void> {
  const docx = await import('docx');
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel,
    AlignmentType, Footer, PageNumber, NumberFormat,
    BorderStyle, convertInchesToTwip,
  } = docx;

  const langCode = overrides?.language ?? 'en';
  const useCustomFont = langCode !== 'en' && !isLatinScript(langCode);

  // ── Load Unicode fonts for DOCX embedding ──────────────────
  let primaryFontName = 'Georgia'; // default for English / Latin
  let secondaryFontName: string | undefined;
  const embeddedFonts: Array<{ name: string; data: ArrayBuffer }> = [];

  if (useCustomFont) {
    try {
      const primaryFont = getFontForLanguage(langCode);
      const primaryBuffer = await fetchFont(primaryFont);
      primaryFontName = primaryFont.name;
      embeddedFonts.push({ name: primaryFont.name, data: primaryBuffer });

      // CJK languages also need the Latin font for mixed-in English terms
      const secondary = getSecondaryFont(langCode);
      if (secondary) {
        const secondaryBuffer = await fetchFont(secondary);
        secondaryFontName = secondary.name;
        embeddedFonts.push({ name: secondary.name, data: secondaryBuffer });
      }
    } catch (err) {
      console.warn(`Failed to load font for ${langCode}, falling back to Georgia:`, err);
      primaryFontName = 'Georgia';
    }
  }

  // Font descriptor for TextRun objects
  const fontDescriptor = useCustomFont && embeddedFonts.length > 0
    ? {
        ascii: secondaryFontName ?? primaryFontName,
        eastAsia: primaryFontName,
        cs: primaryFontName,
        hAnsi: secondaryFontName ?? primaryFontName,
      }
    : undefined;

  const children: InstanceType<typeof Paragraph>[] = [];

  const lines = policy.markdown.split('\n');

  for (const raw of lines) {
    const line = raw.trimEnd();

    if (line.length === 0) {
      children.push(new Paragraph({ text: '' }));
      continue;
    }

    // H1 — title
    if (/^# /.test(line) && !/^## /.test(line)) {
      children.push(new Paragraph({
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        children: [new TextRun({
          text: stripMarkdownInline(line.replace(/^# /, '')),
          bold: true,
          ...(fontDescriptor ? { font: fontDescriptor } : {}),
        })],
        spacing: { after: 200 },
      }));
      continue;
    }

    // H2
    if (/^## /.test(line)) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_1,
        border: { bottom: { color: 'CCCCCC', space: 4, style: BorderStyle.SINGLE, size: 6 } },
        children: [new TextRun({
          text: stripMarkdownInline(line.replace(/^## /, '')),
          bold: true,
          ...(fontDescriptor ? { font: fontDescriptor } : {}),
        })],
        spacing: { before: 300, after: 150 },
      }));
      continue;
    }

    // H3
    if (/^### /.test(line)) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({
          text: stripMarkdownInline(line.replace(/^### /, '')),
          bold: true,
          ...(fontDescriptor ? { font: fontDescriptor } : {}),
        })],
        spacing: { before: 200, after: 100 },
      }));
      continue;
    }

    // Blockquote — disclaimer
    if (/^>\s/.test(line)) {
      children.push(new Paragraph({
        indent: { left: convertInchesToTwip(0.2) },
        spacing: { after: 100 },
        children: [new TextRun({
          text: stripMarkdownInline(line.replace(/^>\s*/, '')),
          italics: true,
          size: 16,
          color: '888888',
          ...(fontDescriptor ? { font: fontDescriptor } : {}),
        })],
      }));
      continue;
    }

    // Italic preamble
    if (/^\*[^*]+\*$/.test(line) && !/\*\*/.test(line)) {
      children.push(new Paragraph({
        spacing: { after: 100 },
        children: [new TextRun({
          text: stripMarkdownInline(line.replace(/^\*/, '').replace(/\*$/, '')),
          italics: true,
          size: 18,
          color: '888888',
          ...(fontDescriptor ? { font: fontDescriptor } : {}),
        })],
      }));
      continue;
    }

    // Bold subtitle
    if (/^\*\*[^*]+\*\*:?\s/.test(line)) {
      children.push(new Paragraph({
        spacing: { after: 80 },
        children: [new TextRun({
          text: stripMarkdownInline(line),
          bold: true,
          size: 18,
          color: '888888',
          ...(fontDescriptor ? { font: fontDescriptor } : {}),
        })],
      }));
      continue;
    }

    // List item
    if (/^[-*]\s+/.test(line)) {
      children.push(new Paragraph({
        bullet: { level: 0 },
        children: parseInlineFormatting(stripNonBoldMarkdown(line.replace(/^[-*]\s+/, '')), TextRun, fontDescriptor),
        spacing: { after: 60 },
      }));
      continue;
    }

    // Ordered list
    if (/^\d+\.\s+/.test(line)) {
      children.push(new Paragraph({
        numbering: { reference: 'default-numbering', level: 0 },
        children: parseInlineFormatting(stripNonBoldMarkdown(line.replace(/^\d+\.\s+/, '')), TextRun, fontDescriptor),
        spacing: { after: 60 },
      }));
      continue;
    }

    // Regular paragraph
    children.push(new Paragraph({
      children: parseInlineFormatting(stripNonBoldMarkdown(line), TextRun, fontDescriptor),
      spacing: { after: 80 },
    }));
  }

  const doc = new Document({
    ...(embeddedFonts.length > 0 ? {
      fonts: embeddedFonts.map((f) => ({
        name: f.name,
        data: new Uint8Array(f.data) as Buffer,
      })),
    } : {}),
    styles: {
      default: {
        document: {
          run: {
            font: primaryFontName,
            size: 22,
          },
        },
      },
    },
    numbering: {
      config: [{
        reference: 'default-numbering',
        levels: [{ level: 0, format: NumberFormat.DECIMAL, text: '%1.', alignment: AlignmentType.START }],
      }],
    },
    sections: [{
      properties: {
        page: {
          margin: { top: convertInchesToTwip(1), bottom: convertInchesToTwip(1), left: convertInchesToTwip(1), right: convertInchesToTwip(1) },
        },
      },
      footers: {
        default: new Footer({
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: `${overrides?.generatedBy ?? 'Generated by PrivacyPolGen.com'}  |  ${overrides?.pageLabel ?? 'Page'} `,
                size: 16,
                color: '999999',
                ...(fontDescriptor ? { font: fontDescriptor } : {}),
              }),
              new TextRun({
                children: [PageNumber.CURRENT],
                size: 16,
                color: '999999',
                ...(fontDescriptor ? { font: fontDescriptor } : {}),
              }),
            ],
          })],
        }),
      },
      children,
    }],
  });

  try {
    const docxFilename = overrides?.filename ?? 'privacy-policy';
    const blob = await Packer.toBlob(doc);
    triggerDownload(blob, `${docxFilename}.docx`);
  } catch (err) {
    console.error('DOCX export failed:', err);
    throw new Error('Failed to generate DOCX: ' + (err instanceof Error ? err.message : String(err)));
  }
}

// Strip markdown except bold (for DOCX inline formatting)
function stripNonBoldMarkdown(text: string): string {
  return text
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1');
}

// Replace emoji characters with text equivalents for PDF rendering
function sanitizeForPdf(text: string): string {
  return text
    .replace(/\u26A0\uFE0F/g, '[!]')    // \u26A0\uFE0F = warning sign
    .replace(/\u26A0/g, '[!]')           // \u26A0 = warning sign (without VS16)
    .replace(/\u2705/g, '[OK]')          // green check mark
    .replace(/\u26D4/g, '[X]')           // no entry
    .replace(/\u2714\uFE0F/g, '[OK]');  // heavy check mark
}

// Simple inline formatting parser for DOCX TextRuns
function parseInlineFormatting(
  text: string,
  TextRun: typeof import("docx").TextRun,
  fontDescriptor?: { ascii: string; eastAsia: string; cs: string; hAnsi: string },
) {
  // Split on bold markers to handle them inline
  const runs: InstanceType<typeof TextRun>[] = [];
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  for (const part of parts) {
    if (/^\*\*[^*]+\*\*$/.test(part)) {
      runs.push(new TextRun({
        text: part.replace(/^\*\*/, '').replace(/\*\*$/, ''),
        bold: true,
        ...(fontDescriptor ? { font: fontDescriptor } : {}),
      }));
    } else if (part) {
      runs.push(new TextRun({
        text: part,
        ...(fontDescriptor ? { font: fontDescriptor } : {}),
      }));
    }
  }
  return runs.length > 0 ? runs : [new TextRun({ text, ...(fontDescriptor ? { font: fontDescriptor } : {}) })];
}
